name: AXIOM-Core
version: 2.0.0
main: com.axiom.core.plugin.AXIOMModular
api-version: 1.20
authors: [An0nimVta, AI]
description: Modular core for AXIOM Geopolitical Engine
commands:
  axiom:
    description: Main command
    usage: /axiom <subcommand>